Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:

ListS3BucketsRole:
    Type: AWS::IAM::Role
    Properties: 
        AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
                - Effect: Allow
                  Principal:
                    Service:
                    - ec2.amazonaws.com
                  Action:
                  - sts:AssumeRole
        Path: "/"
ListS3BucketsPolicy:
    Type: AWS::IAM::Policy
    Properties:
        PolicyName: ListS3BucketsPolicy
        PolicyDocument:
            Statement:
                - Effect: Allow
                  Action:
                  - s3:List*
                  Resource: "*"
        Roles:
        - Ref: ListS3BucketsRole

ListS3BucketsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
        Path: "/"
        Roles:
        - Ref: ListS3BucketsRole